package ship.game.events;

public enum EventType {
    GAME_START,
    TURN_START,
    DRAW_CARD_DECISION,
    GAME_END,
    PASS_DECISION,
    DRAW_CARD,
    CLICK_ON_COIN,
    CLICK_ON_CANNON,
    CLICK_ON_SHIP,
    CLICK_ON_SHIP_COLLECTED,
    SELECT_CARDS_TO_RETURN,
    CARD_PURCHASE_DECISION,
    SET_SHIP_TYPE_TO_COLLECT,
    PLAYER_SWITCHED,

}
